services:
  anveshan-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-6493}:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
